export const LOGIN = 'LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const CHANGE_PASSWORD_PENDING = 'CHANGE_PASSWORD_PENDING';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const CHANGE_EMAIL_PENDING = 'CHANGE_EMAIL_PENDING';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_EMAIL_ERROR = 'CHANGE_EMAIL_ERROR';

export const METRICS_ERROR = 'METRICS_ERROR';
export const RECEIVED_METRICS = 'RECEIVED_METRICS';
export const REQUEST_METRICS = 'REQUEST_METRICS';

export const REHYDRATE = 'persist/REHYDRATE';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const DELETE_SESSION = 'DELETE_SESSION';

export const RECOGNITIONS_ERROR = 'RECOGNITIONS_ERROR';
export const REQUEST_RECOGNITIONS = 'REQUEST_RECOGNITIONS';
export const RECEIVED_RECOGNITIONS = 'RECEIVED_RECOGNITIONS';

export const HEALTH_CHECK_ERROR = 'HEALTH_CHECK_ERROR';
export const REQUEST_HEALTH_CHECK = 'REQUEST_HEALTH_CHECK';
export const RECEIVED_HEALTH_CHECK = 'RECEIVED_HEALTH_CHECK';

export const USERS_ERROR = 'USERS_ERROR';
export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVED_USERS = 'RECEIVED_USERS';
